"""
Transparency — detailed provenance for every data source, AI prompt, and pipeline step.
"""

import streamlit as st
import pandas as pd

from utils.db import load_table_sample

st.title("Transparency")
st.markdown(
    "This page explains where every piece of data on this site comes from, how AI summaries "
    "are generated, and what the underlying database looks like. Nothing is hidden."
)

# ---------------------------------------------------------------------------
# Meetings page
# ---------------------------------------------------------------------------

with st.expander("Meetings page"):

    with st.expander("Meeting list"):
        st.markdown(
            "The meeting list is drawn from the **Legistar API** "
            "(`https://webapi.legistar.com/v1/corpuschristi/`), which is the public records "
            "system used by the City of Corpus Christi. Meeting records are synced into the "
            "`events` table in Supabase via a Python script (`scripts/sync-events.js`). "
            "Only meetings that have a completed transcript are shown in the selector."
        )
        st.markdown(
            "**Fields used:** `event_id`, `event_date`, `body_id` (joined to `bodies.body_name`), "
            "`event_media` (Granicus clip ID, used to locate the video)"
        )

    with st.expander("Transcript"):
        st.markdown("#### Transcription pipeline")
        st.markdown(
            "1. **Locate video** — The `event_media` field on each event holds a Granicus clip ID "
            "(e.g. `2171`). The Granicus player page at "
            "`https://corpuschristi.granicus.com/player/clip/{clipId}` is fetched and a regex "
            "extracts the `.m3u8` stream URL from the page source."
        )
        st.markdown(
            "2. **Download audio** — `ffmpeg` downloads the HLS stream and re-encodes it to MP3."
        )
        st.markdown(
            "3. **Transcribe & diarize** — The MP3 is submitted to "
            "**ElevenLabs Scribe v2** (`POST https://api.elevenlabs.io/v1/speech-to-text`) "
            "with `diarize: true` and `timestamps_granularity: \"word\"`. "
            "The API returns word-level timestamps and assigns each word a speaker label "
            "(`speaker_0`, `speaker_1`, etc.). Consecutive words from the same speaker are "
            "grouped into segments."
        )
        st.markdown(
            "4. **Store segments** — Each speaker turn is stored as a row in `transcript_segments` "
            "with `person_id = NULL`. Speaker labels are arbitrary per recording — "
            "ElevenLabs provides no cross-recording identity."
        )
        st.markdown(
            "5. **Map speakers** — After transcription, the operator runs `map_speakers.py`, "
            "a CLI tool that shows sample utterances for each speaker label and prompts for the "
            "corresponding Person record. This updates `person_id` in `transcript_segments` and "
            "inserts a row into `speaker_mappings`. This step is **manual** — no automatic "
            "speaker identification is performed."
        )
        st.markdown(
            "**Cost:** ~$0.40/hr of audio (ElevenLabs Scribe v2 pricing). "
            "Estimated cost per meeting is stored in `transcripts.cost_usd`."
        )

    with st.expander("Meeting summary (AI-generated)"):
        st.markdown(
            "Meeting summaries are generated by submitting speaker-attributed transcript segments "
            "to the Claude API. **Only segments where a speaker label has been manually mapped to "
            "a Person record are included** — unmapped segments are excluded."
        )
        st.markdown(
            f"**Model:** `claude-opus-4-6`  \n"
            f"**Max input:** 80,000 characters (transcript is truncated if longer)  \n"
            f"**Input format:** `HH:MM | Speaker Name | Statement` (one line per segment)  \n"
            f"**Output stored in:** `meeting_summaries` (`summary_text`, `member_briefs`, `model`, `generated_at`)"
        )
        st.markdown("#### Exact prompt sent to Claude")
        st.code(
            """\
You are summarizing a Corpus Christi City Council meeting for the general public.

Meeting date: {event_date}

Transcript (Time | Speaker | Statement):
{transcript}

Write a structured summary. Respond ONLY with valid JSON in exactly this structure:
{
  "overview": "2-3 sentence overview of what was discussed and decided at this meeting",
  "members": {
    "<person_id as string>": {
      "name": "Full name",
      "summary": "2-4 sentences describing what this council member focused on and their positions",
      "quotes": ["direct quote 1", "direct quote 2", "direct quote 3"]
    }
  }
}

Rules:
- Include only council members who actually spoke (exclude City Manager, City Attorney, staff, public commenters)
- Quotes must be verbatim from the transcript
- Keep the overview factual and neutral
- Do not include any text outside the JSON""",
            language="text",
        )

    with st.expander("Council member perspectives (AI-generated)"):
        st.markdown(
            "The council member perspectives shown in the 'Council Member Perspectives' expander "
            "are **not a separate API call** — they come from the `members` key in the same JSON "
            "response as the meeting overview. The same prompt and the same Claude call produces both."
        )
        st.markdown(
            "Each member's brief (`summary` + `quotes`) is stored in the `member_briefs` JSONB "
            "column of `meeting_summaries`, keyed by `person_id`. A member only appears if they "
            "spoke in segments that were speaker-mapped before the summary was generated."
        )

# ---------------------------------------------------------------------------
# Persons page
# ---------------------------------------------------------------------------

with st.expander("Persons page"):

    with st.expander("Profile & term history"):
        st.markdown(
            "Profile data comes from the Legistar API — specifically the `Persons` and "
            "`OfficeRecords` endpoints. The `office_records` table stores every role a person "
            "has held in a governing body (title, start date, end date). The app filters to "
            "records where the body is 'City Council' and shows all terms."
        )
        st.markdown(
            "**Fields used:** `persons.person_full_name`, `persons.person_email`, "
            "`office_records.office_record_title`, `office_records.office_record_start_date`, "
            "`office_records.office_record_end_date`"
        )

    with st.expander("Voting record"):
        st.markdown(
            "Voting data comes from the Legistar `EventItemVotes` endpoint and is stored in the "
            "`votes` table. Each row records one person's vote on one agenda item."
        )
        st.markdown(
            "**Important:** Legistar assigns one `VoteId` per person per *meeting*, not per item. "
            "The same `VoteId` appears on every agenda item voted on that day. The primary key "
            "is therefore composite: `(vote_id, event_item_id)` — `vote_id` alone is not unique."
        )
        st.markdown(
            "**Joins used:** `votes` → `event_items` → `events` (for date), "
            "`event_items` → `matters` (for agenda item title)"
        )
        st.markdown(
            "**Vote values:** Aye, Nay, Absent, Abstain, Recused, Present — as returned by Legistar."
        )

    with st.expander("AI summary (rolling)"):
        st.markdown(
            "The 'About [member]' summary is a **rolling summary** — it reflects all transcript "
            "segments attributed to that person across every transcribed meeting, not just one. "
            "It is regenerated whenever a new meeting is transcribed and speaker-mapped."
        )
        st.markdown(
            f"**Model:** `claude-opus-4-6`  \n"
            f"**Max input:** 80,000 characters  \n"
            f"**Input format:** `YYYY-MM-DD | Statement` (one line per segment, sorted by event)  \n"
            f"**Output stored in:** `member_summaries` (`summary_text`, `quotes`, `model`, `generated_at`)"
        )
        st.markdown(
            "**Coverage:** Only reflects meetings that have been transcribed **and** where this "
            "person's speaker label has been manually mapped. Members who have not spoken in any "
            "transcribed meeting will have no summary."
        )
        st.markdown("#### Exact prompt sent to Claude")
        st.code(
            """\
You are summarizing a Corpus Christi City Council member's record across multiple meetings.

Council member: {person_name}
Statements across {n_meetings} meeting(s) (Date | Statement):
{statements}

Write a summary of this council member's record. Respond ONLY with valid JSON in exactly this structure:
{
  "summary": "3-5 sentences describing what issues this council member consistently focuses on, their general positions and values, and any notable patterns in how they engage",
  "quotes": [
    {"text": "verbatim quote", "event_id": 123, "event_date": "YYYY-MM-DD"},
    {"text": "verbatim quote", "event_id": 124, "event_date": "YYYY-MM-DD"},
    {"text": "verbatim quote", "event_id": 125, "event_date": "YYYY-MM-DD"}
  ]
}

Rules:
- Choose 3-5 quotes that best illustrate their record and positions
- Quotes must be verbatim from the statements provided
- The summary should be factual, neutral, and based only on the statements provided
- Do not include any text outside the JSON""",
            language="text",
        )

    with st.expander("Statements"):
        st.markdown(
            "The Statements expander shows transcript segments from `transcript_segments` where "
            "`person_id` matches the selected council member. Segments are only attributed to a "
            "person after the manual speaker-mapping step described above."
        )
        st.markdown(
            "Statements are limited to meetings that have been transcribed. The text is verbatim "
            "from ElevenLabs Scribe v2 — no post-processing or correction is applied."
        )

# ---------------------------------------------------------------------------
# Database schema
# ---------------------------------------------------------------------------

with st.expander("Database schema"):
    st.markdown(
        "All data is stored in a [Supabase](https://supabase.com) (PostgreSQL) database. "
        "All tables have public read access (anonymous key can SELECT, not write). "
        "The live data samples below are fetched directly from the database."
    )

    TABLES = [
        {
            "name": "bodies",
            "description": "Governing bodies — City Council, boards, committees, and other bodies tracked in Legistar.",
            "fields": [
                ("body_id", "INTEGER PK", "Legistar BodyId — stable unique identifier"),
                ("body_name", "TEXT", "Full name of the body (e.g. 'City Council')"),
                ("body_type", "TEXT", "Category (e.g. 'City Council', 'Board', 'Commission')"),
                ("body_description", "TEXT", "Optional description from Legistar"),
                ("body_active_flag", "BOOLEAN", "Whether the body is currently active"),
                ("body_meet_day", "TEXT", "Typical meeting day (e.g. 'Tuesday')"),
                ("body_meet_time", "TEXT", "Typical meeting time"),
                ("body_meet_location", "TEXT", "Typical meeting location"),
                ("body_last_modified", "TIMESTAMPTZ", "Last modified timestamp from Legistar"),
            ],
        },
        {
            "name": "persons",
            "description": "All individuals who appear in Legistar — council members, staff, city attorneys, and others.",
            "fields": [
                ("person_id", "INTEGER PK", "Legistar PersonId — stable unique identifier"),
                ("person_full_name", "TEXT", "Full display name"),
                ("person_first_name", "TEXT", "First name"),
                ("person_last_name", "TEXT", "Last name"),
                ("person_email", "TEXT", "Email address (may be null)"),
                ("person_phone", "TEXT", "Phone number (may be null)"),
                ("person_active_flag", "BOOLEAN", "Whether the person is currently active in Legistar"),
                ("person_last_modified", "TIMESTAMPTZ", "Last modified timestamp from Legistar"),
            ],
        },
        {
            "name": "matters",
            "description": "Agenda items, ordinances, resolutions, and other legislative matters tracked in Legistar.",
            "fields": [
                ("matter_id", "INTEGER PK", "Legistar MatterId"),
                ("matter_file", "TEXT", "File number (e.g. '24-0123')"),
                ("matter_name", "TEXT", "Short name or code"),
                ("matter_title", "TEXT", "Full descriptive title of the matter"),
                ("matter_type", "TEXT", "Type (Ordinance, Resolution, Contract, etc.)"),
                ("matter_status", "TEXT", "Current status (Passed, Failed, Tabled, etc.)"),
                ("matter_body_name", "TEXT", "Name of the body responsible for this matter"),
                ("matter_intro_date", "DATE", "Date introduced"),
                ("matter_agenda_date", "DATE", "Date placed on an agenda"),
                ("matter_passed_date", "DATE", "Date passed (if applicable)"),
                ("matter_enactment_number", "TEXT", "Ordinance or resolution number after passage"),
                ("matter_last_modified", "TIMESTAMPTZ", "Last modified timestamp from Legistar"),
            ],
        },
        {
            "name": "events",
            "description": "Individual meetings — one row per meeting session, linked to a governing body.",
            "fields": [
                ("event_id", "INTEGER PK", "Legistar EventId"),
                ("body_id", "INTEGER FK → bodies", "The body that held this meeting"),
                ("event_date", "DATE", "Date of the meeting"),
                ("event_time", "TEXT", "Start time"),
                ("event_location", "TEXT", "Meeting location"),
                ("event_agenda_status", "TEXT", "Status of the agenda document"),
                ("event_minutes_status", "TEXT", "Status of the minutes document"),
                ("event_agenda_file", "TEXT", "URL to the agenda PDF"),
                ("event_minutes_file", "TEXT", "URL to the minutes PDF"),
                ("event_in_site_url", "TEXT", "Legistar public web page for this meeting"),
                ("event_video_path", "TEXT", "Video path from Legistar (often empty)"),
                ("event_media", "TEXT", "Granicus clip ID — used to locate the video stream for transcription"),
                ("event_last_modified", "TIMESTAMPTZ", "Last modified timestamp from Legistar"),
            ],
        },
        {
            "name": "matter_attachments",
            "description": "Supporting documents attached to matters — staff reports, exhibits, resolutions, etc.",
            "fields": [
                ("attachment_id", "INTEGER PK", "Legistar MatterAttachmentId"),
                ("matter_id", "INTEGER FK → matters", "The matter this attachment belongs to"),
                ("attachment_name", "TEXT", "Display name of the document"),
                ("attachment_hyperlink", "TEXT", "URL to the document"),
                ("attachment_is_supporting", "BOOLEAN", "Whether this is a supporting (vs. primary) document"),
                ("attachment_last_modified", "TIMESTAMPTZ", "Last modified timestamp from Legistar"),
            ],
        },
        {
            "name": "event_items",
            "description": "Agenda items for a specific meeting — connects events to matters and records actions taken.",
            "fields": [
                ("event_item_id", "INTEGER PK", "Legistar EventItemId"),
                ("event_id", "INTEGER FK → events", "The meeting this item appeared on"),
                ("matter_id", "INTEGER FK → matters, nullable", "The matter being considered (null for procedural items)"),
                ("event_item_title", "TEXT", "Title of the agenda item"),
                ("event_item_agenda_number", "INTEGER", "Item number on the agenda"),
                ("event_item_action_name", "TEXT", "Action taken (e.g. 'Approved', 'Tabled')"),
                ("event_item_result", "TEXT", "Outcome (e.g. 'Pass', 'Fail')"),
                ("event_item_agenda_note", "TEXT", "Notes from the agenda"),
                ("event_item_minutes_note", "TEXT", "Notes from the minutes"),
                ("event_item_last_modified", "TIMESTAMPTZ", "Last modified timestamp from Legistar"),
            ],
        },
        {
            "name": "votes",
            "description": "Each council member's vote on each agenda item. Composite PK — VoteId alone is not unique.",
            "fields": [
                ("vote_id", "INTEGER (part of composite PK)", "Legistar VoteId — assigned once per person per meeting, not per item"),
                ("event_item_id", "INTEGER FK → event_items (part of composite PK)", "The specific agenda item voted on"),
                ("person_id", "INTEGER FK → persons, nullable", "The voter (null if Legistar person could not be matched)"),
                ("vote_person_name", "TEXT", "Fallback name when person_id is null"),
                ("vote_value_name", "TEXT", "How the person voted: Aye, Nay, Absent, Abstain, Recused, Present"),
                ("vote_result", "TEXT", "Overall result of the vote: Pass or Fail"),
                ("vote_last_modified", "TIMESTAMPTZ", "Last modified timestamp from Legistar"),
            ],
        },
        {
            "name": "office_records",
            "description": "A person's role in a governing body over a time period — each term or title change is a separate row.",
            "fields": [
                ("office_record_id", "INTEGER PK", "Legistar OfficeRecordId"),
                ("person_id", "INTEGER FK → persons", "The person holding the office"),
                ("body_id", "INTEGER FK → bodies", "The body they served in"),
                ("office_record_title", "TEXT", "Title held (e.g. 'Council Member', 'Mayor', 'Mayor Pro Tem')"),
                ("office_record_start_date", "DATE", "Start of this term or role"),
                ("office_record_end_date", "DATE, nullable", "End of this term (null = currently serving)"),
                ("office_record_member_type", "TEXT", "Member type classification from Legistar"),
                ("office_record_last_modified", "TIMESTAMPTZ", "Last modified timestamp from Legistar"),
            ],
        },
        {
            "name": "transcripts",
            "description": "One record per transcribed meeting — tracks the pipeline status, video URL, duration, and cost.",
            "fields": [
                ("transcript_id", "SERIAL PK", "Auto-incrementing internal ID"),
                ("event_id", "INTEGER FK → events, UNIQUE", "The meeting this transcript belongs to"),
                ("m3u8_url", "TEXT", "HLS stream URL extracted from the Granicus player page"),
                ("status", "TEXT", "Pipeline status: pending | processing | complete | error"),
                ("error_message", "TEXT, nullable", "Error details if status = error"),
                ("duration_seconds", "NUMERIC", "Length of audio in seconds"),
                ("cost_usd", "NUMERIC", "Estimated ElevenLabs transcription cost"),
                ("created_at", "TIMESTAMPTZ", "When this record was created"),
                ("completed_at", "TIMESTAMPTZ, nullable", "When transcription finished"),
            ],
        },
        {
            "name": "transcript_segments",
            "description": "One row per speaker turn in a transcript — the raw output of the transcription pipeline.",
            "fields": [
                ("segment_id", "BIGSERIAL PK", "Auto-incrementing internal ID"),
                ("transcript_id", "INTEGER FK → transcripts", "Parent transcript"),
                ("event_id", "INTEGER FK → events", "Denormalized meeting reference for easier querying"),
                ("person_id", "INTEGER FK → persons, nullable", "Null until the speaker label is manually mapped"),
                ("speaker_label", "TEXT", "ElevenLabs label (e.g. 'speaker_0') — arbitrary per recording"),
                ("start_time", "NUMERIC", "Start of this turn in decimal seconds"),
                ("end_time", "NUMERIC", "End of this turn in decimal seconds"),
                ("segment_text", "TEXT", "Verbatim transcript of this speaker turn"),
            ],
        },
        {
            "name": "speaker_mappings",
            "description": "Manual mapping of a speaker label to a Person record for a given transcript.",
            "fields": [
                ("mapping_id", "SERIAL PK", "Auto-incrementing internal ID"),
                ("transcript_id", "INTEGER FK → transcripts", "The transcript this mapping applies to"),
                ("speaker_label", "TEXT", "The label assigned by ElevenLabs (e.g. 'speaker_0')"),
                ("person_id", "INTEGER FK → persons", "The Person this label was identified as"),
            ],
        },
        {
            "name": "meeting_summaries",
            "description": "AI-generated overview and per-member briefs for a meeting. One row per transcript.",
            "fields": [
                ("summary_id", "SERIAL PK", "Auto-incrementing internal ID"),
                ("transcript_id", "INTEGER FK → transcripts, UNIQUE", "The transcript this summary covers"),
                ("event_id", "INTEGER FK → events", "Denormalized meeting reference"),
                ("summary_text", "TEXT", "2-3 sentence overview of the meeting"),
                ("member_briefs", "JSONB", "Dict keyed by person_id; each value has name, summary, and quotes array"),
                ("model", "TEXT", "Claude model ID used to generate this summary"),
                ("generated_at", "TIMESTAMPTZ", "When this summary was generated"),
            ],
        },
        {
            "name": "member_summaries",
            "description": "Rolling AI-generated summary of a council member's record across all transcribed meetings.",
            "fields": [
                ("member_summary_id", "SERIAL PK", "Auto-incrementing internal ID"),
                ("person_id", "INTEGER FK → persons, UNIQUE", "The council member"),
                ("summary_text", "TEXT", "3-5 sentence narrative of their focus areas and positions"),
                ("quotes", "JSONB", "Array of 3-5 verbatim quotes, each with text, event_id, and event_date"),
                ("model", "TEXT", "Claude model ID used to generate this summary"),
                ("generated_at", "TIMESTAMPTZ", "When this summary was last generated"),
            ],
        },
    ]

    for table in TABLES:
        with st.expander(f"`{table['name']}`"):
            st.caption(table["description"])

            field_df = pd.DataFrame(table["fields"], columns=["Field", "Type", "Description"])
            st.dataframe(field_df, use_container_width=True, hide_index=True)

            st.markdown("**Live data sample** (first 50 rows)")
            with st.spinner(f"Loading {table['name']}..."):
                sample_df = load_table_sample(table["name"], limit=50)
            if sample_df.empty:
                st.caption("No data yet.")
            else:
                st.dataframe(sample_df, use_container_width=True, hide_index=True)
                st.caption(f"Showing up to 50 rows · data is live from Supabase")
